# Generated by Django 2.2.16 on 2022-06-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created"],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.RenameField(
            model_name="post",
            old_name="pub_date",
            new_name="created",
        ),
    ]
