# Generated by Django 2.2.16 on 2022-06-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_rename_field_pub_date_on_post_to_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время публикации: автоматическое поле",
                verbose_name="Дата и время публикации",
            ),
        ),
    ]
