# Generated by Django 2.2.16 on 2022-06-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_follow"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("author", "user"), name="unique_following"
            ),
        ),
    ]
