# Generated by Django 2.2.16 on 2022-07-16 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_add_constraint_unique_following"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите хештег",
                        max_length=32,
                        verbose_name="Хештег",
                    ),
                ),
            ],
            options={
                "verbose_name": "Хештег",
                "verbose_name_plural": "Хештеги",
            },
        ),
        migrations.CreateModel(
            name="TagPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.Post",
                        verbose_name="Текст сообщения",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.Tag",
                        verbose_name="Хештег",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(
                help_text="Введите хештег",
                through="posts.TagPost",
                to="posts.Tag",
                verbose_name="Хештег",
            ),
        ),
    ]
